import Head from "next/head";
import type { AppProps } from 'next/app'
import { createEmotionSsrAdvancedApproach } from "tss-react/nextJs";
import marianneLightWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Light.woff2";
import marianneItalicWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Light_Italic.woff2";
import marianneRegularWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Regular.woff2";
import marianneRegularItalicWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Regular_Italic.woff2";
import marianneMediumWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Medium.woff2";
import marianneMediumItalicWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Medium_Italic.woff2";
import marianneBoldWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Bold.woff2";
import marianneBoldItalicWoff2Url from "react_dsfr/dsfr/fonts/Marianne-Bold_Italic.woff2";
import spectralRegularWoff2Url from "react_dsfr/dsfr/fonts/Spectral-Regular.woff2";
import spectralExtraBoldWoff2Url from "react_dsfr/dsfr/fonts/Spectral-ExtraBold.woff2";
import { startReactDsfr } from "react_dsfr";
import "react_dsfr/dsfr/dsfr.css";

startReactDsfr({ "defaultColorScheme": "system" });

const { EmotionCacheProvider, withEmotionCache } = createEmotionSsrAdvancedApproach({ "key": "css" });

export { withEmotionCache };

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Next DSFR!</title>
				<meta name="description" content="Generated by create next app" />
				{[
					marianneLightWoff2Url,
					marianneItalicWoff2Url,
					marianneRegularWoff2Url,
					marianneRegularItalicWoff2Url,
					marianneMediumWoff2Url,
					marianneMediumItalicWoff2Url,
					marianneBoldWoff2Url,
					marianneBoldItalicWoff2Url,
					spectralRegularWoff2Url,
					spectralExtraBoldWoff2Url
				].map(href => <link key={href} rel="preload" href={href} as="font" crossOrigin="anonymous" />)}
			</Head>
			<EmotionCacheProvider>
				<Component {...pageProps} />
			</EmotionCacheProvider>
		</>
	);
}
