import Head from "next/head";
import { createEmotionSsrAdvancedApproach } from "tss-react/nextJs";
import Index from "./index";
import Script from 'next/script'
import "react_dsfr/assets/gouvfr_dsfr_dist/dsfr.css";

const { EmotionCacheProvider, withEmotionCache } = createEmotionSsrAdvancedApproach({ "key": "css" });

export { withEmotionCache };

export default function App() {
	return (
		<>
			<Head>
				<title>Next DSFR!</title>
				<meta name="description" content="Generated by create next app" />
				{/*<link rel="stylesheet" href="/normalize.css" />*/}
			</Head>
			<EmotionCacheProvider>
				<Index />
			</EmotionCacheProvider>
			<Script>{`window.dsfr = { "verbose": true, "mode": "manual" };`}</Script>
			<Script type="module" src="gouvfr_dsfr_dist/dsfr.module.min.js" />
    		<Script type="text/javascript" noModule src="gouvfr_dsfr_dist/dsfr.nomodule.min.js"/>
		</>
	);

}
